name: CI

on:
  pull_request:
  push:

jobs:

  host-build:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt and build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            g++ \
            nodejs \
            npm \
            python3-pip \
            libcurl4-openssl-dev \
            qt6-base-dev \
            qt6-base-dev-tools \
            qt6-tools-dev \
            libgl1-mesa-dev

      - name: Install codegen dependencies
        run: |
          npm i lv_font_conv -g
          pip3 install jinja2 pyyaml

      - name: Configure unit test
        run: cmake -S test/unittest -B build-unittest -GNinja -DCMAKE_BUILD_TYPE=Debug

      - name: Build unit tests
        run: cmake --build build-unittest --parallel

      - name: Run unit tests
        run: ctest --test-dir build-unittest --output-on-failure
